version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: mysql-clinic
    restart: always
    environment:
      POSTGRES_DB: clinic_db
      POSTGRES_USER: clinic_user
      POSTGRES_PASSWORD: root_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  mysql:
#    image: mysql:8.0
#    container_name: mysql-clinic
#    restart: unless-stopped
#    environment:
#      MYSQL_ROOT_PASSWORD: root_password
#      MYSQL_DATABASE: clinic_db
#      MYSQL_USER: clinic_user
#      MYSQL_PASSWORD: clinic_password
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql


  kotlin-app:
    build: .
    container_name: kotlin_app
    restart: unless-stopped  # Jeśli chcesz, by aplikacja restartowała się po awarii
    environment:
      DB_URL: "jdbc:postgresql://postgresql:3306/clinic_db"  # Używamy 'mysql' jako nazwy usługi
      DB_USER: clinic_user
      DB_PASSWORD: clinic_password
    ports:
      - "8080:8080"


volumes:
   postgres_data:

